customadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name ='customadmin'

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', admin_login , name = "admin_login"),
    path('dashboard/', dashboard , name = "dashboard"),

]

home/urls.py
from django.urls import path, include


from . import views
from rest_framework import routers

app_name = 'home'
rr = routers.DefaultRouter()
rr.register('', views.orderitem)

rrr = routers.DefaultRouter()
rrr.register('', views.order)


r = routers.DefaultRouter()
r.register('', views.product)

urlpatterns = [
    path('ca/', views.cart, name='cart'),
    path('Category/', views.Category_listAPI, name='category'),
    path('Category/<int:id>', views.Category_detail, name='category_detail'),

    path('Category/list/', views.Categories_listAPI, name='category'),
    path('Categories/<int:id>', views.Categories_detail, name='category_detail'),

    path('', views.product_listAPI, name='product_list'),
    path('product/<int:id>', views.product_detail, name='product_detail'),

    path('cart/', views.Order_list, name='shopping_cart'),
    path('order/', include(rrr.urls)),
    path('itemorder/', include(rr.urls)),
    path('Recommended/', views.Recommended_listAPI, name='Recommended'),
    path('productAPI/', include(r.urls)),
    path('addcart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('removecart/<int:product_id>/', views.remove_cart, name='remove_cart'),
    path('removecart_item/<int:product_id>/',
         views.remove_cart_item, name='remove_cart_item'),



]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('authentications.urls', namespace='accounts')),
    path('admin/', include('customadmin.urls')),
    path('dj-admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('users/', include('authentications.urls')),
    path('verification/', include('verify_email.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
]

customadmin/models.py
from django.db import models

# Create your models here.

customadmin/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login
from django.contrib import messages
from django.http import HttpResponseRedirect , HttpResponse

def admin_login(request):
    try:
        if request.user.is_authenticated:
            return redirect('/dashboard/')
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user_obj = User.objects.filter(username=username)
            if not user_obj.exists ():
                messages.info(request,'Account not found')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            user_obj = authenticate(username=username,password=password)
            if user_obj and user_obj.is_superuser:
                login(request,user_obj)
                return redirect('/dashboard/')
            messages.info(request,'Invalid Password')
            return redirect('/')
        return render(request,'login.html')
    except Exception as e :
        print(e)

def dashboard(request):
    return render(request,'index.html')

customadmin/templates/login.html
{% load bootstrap4 %}
{% load static %}

<form method="post" >
  {% csrf_token %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Modernize Free</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/logos/favicon.png' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}" />
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <div
      class="position-relative overflow-hidden radial-gradient min-vh-100 d-flex align-items-center justify-content-center">
      <div class="d-flex align-items-center justify-content-center w-100">
        <div class="row justify-content-center w-100">
          <div class="col-md-8 col-lg-6 col-xxl-3">
            <div class="card mb-0">
              <div class="card-body">
                <a href="{% static 'index.html' %}" class="text-nowrap logo-img text-center d-block py-3 w-100">
                  <img src="{% static 'assets/images/logos/dark-logo.svg' %}" width="180" alt="">
                </a>
                <p class="text-center">Your Social Campaigns</p>
                <form>
                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    <input type="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-4">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1">
                  </div>
                  <div class="d-flex align-items-center justify-content-between mb-4">
                    <div class="form-check">
                      <input class="form-check-input primary" type="checkbox" value="" id="flexCheckChecked" checked>
                      <label class="form-check-label text-dark" for="flexCheckChecked">
                        Remeber this Device
                      </label>
                    </div>
                    <a class="text-primary fw-bold" href="./index.html">Forgot Password ?</a>
                  </div>
                  <a href="{% url 'customadmin:dashboard' %}" class="btn btn-primary w-100 py-8 fs-4 mb-4 rounded-2">Sign In</a>
                  <div class="d-flex align-items-center justify-content-center">
                    <p class="fs-4 mb-0 fw-bold">New to Modernize?</p>
                    <a class="text-primary fw-bold ms-2" href="{% static 'authentication-register.html' %}">Create an account</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="../assets/libs/jquery/dist/jquery.min.js"></script>
  <script src="../assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>
</form>